name: pokemon_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.5.0
  firebase_core: ^1.24.0
  counter: ^0.2.2
  animated_text_kit: ^4.2.2
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/pokemon/
  fonts:
    - family: Pocket
      fonts:
        - asset: asset/fonts/Pocket-Monk.ttf

    - family: Silkscreen
      fonts:
        - asset: asset/fonts/Silkscreen-Regular.ttf
